### PR TITLE
Update Lists.md

### PR DESCRIPTION
**Pull request by luharinos**
This PR solves issue #2

### CODE REVIEW

**Review by yochannah — APPROVED** [review]
@er-raoniz you have been busy with PRs - thank you so much! :sparkles: if you would like some InterMine stickers as a thanks, please send me your physical mailing address to yo@intermine.org and I'll send some over :1st_place_medal:

**Comment by luharinos** [comment]
Thanks a lot! @yochannah I would love to have the stickers! :heart:
By physical mailing address, do you mean the residential address?
I guess mailing would be costly? Coz, I am a citizen of [India](https://en.wikipedia.org/wiki/India). :sweat_smile:

**Comment by yochannah** [comment]
Yes! Or some people prefer a work address. :)

**Comment by luharinos** [comment]
I have mailed you the address. Kindly do mail the bills in advance if anything needs to be paid.
Thanks! 😄

**Pull request merged**
